### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mwittgen**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Dev release need to go on a separate label. Not sure if that was done here or not.

**Comment by erykoff** [comment]
This is a rebase to update the dev label.  Is there something else that has to be done?

**Comment by mwittgen** [comment]
linux_aarch64 failed on preparing the pipeline, not the changes. I guess I don't have the permissions to  restart it?

**Comment by erykoff** [comment]
https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-restart-ci
@conda-forge-admin, please restart ci

**Pull request merged**
