### PR TITLE
Bump build number.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
Note: accidentally pushed the real change directly to the branch instead of using a PR.

**Review by timj — APPROVED** [review]
The PR doesn't tell me what the purpose of this change is but it seems this is pinning the compiler on macOS for older versions?

**Comment by ktlim** [comment]
Applying pins from the master branch to 0.4.3, yes.  That includes the macOS libcxx and the galsim pins.

**Pull request merged**
