### PR TITLE
Remove pdbpp which is broken and unsupported on python>3.10.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Ohhhh no!

**Review by ktlim — APPROVED** [review]
While removing a package formally makes us incompatible with previous builds, this was never working anyway, so I'm OK with it.

**Comment by erykoff** [comment]
hmm.  Would it be a problem to install the new build over the old build, or will it just remove the broken packages?

**Pull request merged**
