### PR TITLE
DM-43113: Constrain mpi4py builds.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
Hm.  As to the lint, this is not a selector.  I think the syntax is correct for a build constraint.

**Comment by beckermr** [comment]
You want something like 

run_constrained:
  - impi == 99999999999@9


You can't simply exclude specific mpi4py builds since on any version you'd have to update the excluded build by adding more.

**Comment by beckermr** [comment]
The Linux x86 job has mpich so lgtm!

**Review by erykoff — APPROVED** [review]

**Pull request merged**
