### PR TITLE
Update to python=3.10, cfitsio=4, numpy=1.21

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
IT SOLVES

**Review by ktlim — APPROVED** [review]
Best practice is to rerender before merging, even if it does nothing.

**Comment by timj** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
I'm planning on closing this in favor of #60 if that passes.

**Pull request merged**
