### PR TITLE
Add build for osx-arm64

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
Now that `git-lfs` is officially released for `osx-arm64`, the entire `rubinenv` can be built for `osx-arm64` without any modifications.

**Review by ktlim — APPROVED** [review]
Looks good (after a quick read about conda-forge.yml).

**Comment by erykoff** [comment]
@ktlim Is there anything holding this from being merged?  Thanks!

**Comment by ktlim** [comment]
I was hoping one of the other owners would weigh in.  @timj ?

**Review by timj — APPROVED** [review]
I obviously strongly endorse this. Sorry, didn't realize I was blocking it.

**Comment by erykoff** [comment]
Thanks all!

**Pull request merged**
