### PR TITLE
DM-33469: Try updating to Python 3.10.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Review by timj — APPROVED** [review]

**Comment by timj** [comment]
Linux failure:

```
- Encountered problems while solving:
-   - package rubin-env-nosysroot-2.0.0dev-h25a3098_1 requires pysynphot, but none of the providers can be installed
-   - package pysynphot-1.0.1-py37hb1e94ed_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed```

**Comment by ktlim** [comment]
Yes.  One of us is posting here; one of us is posting to DM-33469 :)

**Comment by erykoff** [comment]
Also we have to use `numpy=1.21`.

**Comment by ktlim** [comment]
@erykoff has a more complete solution in #59.  Closing this one.

**Pull request closed without merging**
