### PR TITLE
Fix some package churn

### PR DESCRIPTION
**Pull request by athornton**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by athornton** [comment]
@conda-forge-admin, please rerender

**Comment by athornton** [comment]
We may need to include jupyterlab_iframe by hand, though.  Investigating.

**Review by ktlim — APPROVED** [review]
Looks OK, only affects -rsp.

**Review by timj — COMMENTED** [review]
Given we are adding a package shouldn't this change the version number?

**Comment by ktlim** [comment]
No, changes to `-rsp` or `-developer` can be done with a build alone.

**Pull request merged**
