### PR TITLE
Update rubin-env to 4.0.0 and include rubin-env-extras.

### PR DESCRIPTION
**Pull request by ktlim**
- Update to python 3.10 (#78).
- Add PyLD, skyproj.
- Add rubin-env-extras output including packages from sciplat-lab, shared_stack, sims, and add in imagemagick and ffmpeg.
- Update cfitsio to 4.1.0 (#79) and flake8 to 4.0.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Looks good to me! Glad to see DM moving to python 3.10. One minor comment is that we have a rubin-sim conda package (https://github.com/conda-forge/rubin-sim-feedstock). IDK if that is the same or different from stuff that is supposed to be captured here. If the deps added here are for that package, you might consider depending on the conda package and letting it manage its own deps.

**Comment by ktlim** [comment]
Yes, these are taken from rubin-sim, but there's no strict requirement that we always be able to support the combination of both rubin-sim and rubin-env in the same environment -- it's only a goal.  So depending explicitly on it would I think mean unnecessary breakage.

**Comment by ktlim** [comment]
Although we are very nearly congruent right now; if I did `rubin-sim [not aarch64]`, I think everything would be OK.

**Review by erykoff — APPROVED** [review]

**Comment by ktlim** [comment]
Nope, rubin-sim appears to not yet be py3.10-compatible, so I reverted.

**Pull request merged**
