### PR TITLE
DM-45920: Pin setuptools <72 for rubinenv 8

### PR DESCRIPTION
**Pull request by mwittgen**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mwittgen** [comment]
@conda-forge-admin, please rerender

**Comment by timj** [comment]
I think rubin-env 8 needs a lower version than 72.1.0 because spectractor will break with 72.

**Review by erykoff — APPROVED** [review]

**Comment by timj** [comment]
I think you need `<72` for rubin-env 8.

See [DM-45562](https://rubinobs.atlassian.net/browse/DM-45562)

**Review by timj — CHANGES_REQUESTED** [review]
Should be `<72` for this one.

**Comment by mwittgen** [comment]
@conda-forge-admin, please rerender

**Review by timj — APPROVED** [review]

**Pull request merged**
