### PR TITLE
DM-44687: Avoid bad git version.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Review by beckermr — CHANGES_REQUESTED** [review]
Why is this version bad? If something is really broken, a pr marking the package as broken should be submitted to admin-requests.

**Comment by timj** [comment]
@beckermr related to https://github.com/git-lfs/git-lfs/issues/5749

**Comment by beckermr** [comment]
Ah ok. That is a bug, not a packaging issue. LGTM!

**Review by beckermr — APPROVED** [review]

**Pull request merged**
