### PR TITLE
DM-38438: Pin doxygen to avoid segfault.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Review by erykoff — APPROVED** [review]

**Comment by beckermr** [comment]
Is this specific to the stack or do we need to mark it broken for all of conda forge in order to be good community members?

**Comment by erykoff** [comment]
Unclear. I (at least) haven’t had any time to see if this is us or them.

**Comment by ktlim** [comment]
Not sure.  There seems to have been [a change in the segfaulting code yesterday|https://github.com/doxygen/doxygen/commit/db830ae3fcf2307397d0c166ed551b22830d8f2e] that might be fixing a bug in the refactoring ("Optimize fragment inclusion performance for INLINE_SOURCES=YES"), but it's not clear if we're doing something wrong with inline code line numbers.

**Pull request merged**
