### PR TITLE
Change channel target for dev build.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
Not exactly sure what the version/build numbers should be in this branch.  Experts?

**Comment by beckermr** [comment]
I am no expert and IDK what the project needs, but typically one would use a dev version on this branch. See the ones that end in rc or dev in the version ordering in the conda docs: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#version-ordering

**Comment by timj** [comment]
so `2.0.0dev1` ? (I assume the dev is relative to the upcoming full release)

**Comment by ktlim** [comment]
It wasn't clear to me if we wanted this for additions (like spherematch) and platform changes (like linux-aarch64) rather than a new major release.

**Comment by ktlim** [comment]
But if it's for Py3.10, that definitely does need a 2.0.0dev.  How would we use the `1` suffix if we already have builds?

**Comment by timj** [comment]
Are we going to need v1.0.0dev and v2.0.0dev branches then? Would we have different dev channels or something?I was hoping for a py3.10 test channel so we can demonstrate that things work in order to aid the RFC process.

**Comment by ktlim** [comment]
Yeah, seems like the additions can easily be tested for solves locally without creating an actual dev build, so reserving this for Py3.10 is appropriate.

**Pull request merged**
