### PR TITLE
DM-33545: Add spherematch and pin cfitsio=4.

### PR DESCRIPTION
**Pull request by ktlim**
Implements RFC-824 and RFC-826.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin restart ci

**Comment by erykoff** [comment]
@ktlim would it be crazy to use this PR to add me as a maintainer on rubinenv?

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Review by timj — APPROVED** [review]

**Pull request merged**
