### PR TITLE
DM-33404: Add prmon to environment 0.8.0

### PR DESCRIPTION
**Pull request by timj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timj** [comment]
@conda-forge-admin, please rerender

**Review by ktlim — APPROVED** [review]
LGTM.

**Comment by ktlim** [comment]
But we should back-port the compilers fix, either by rebasing this on the about-to-be-back-ported 0.7.0 or re-creating the fix.

**Comment by timj** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
