### PR TITLE
DM-30997: Pin galsim minor version.

### PR DESCRIPTION
**Pull request by ktlim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Why is this needed? Version 2.3 has the .so files for linking.

**Comment by ktlim** [comment]
Because binaries have been built against 2.2, and we would like them to continue to function.

**Comment by beckermr** [comment]
I suspect the two versions are ABI compatible. Did you find they are not?

**Comment by ktlim** [comment]
The library version is baked into `libmeas_extensions_shapeHSM`.  `ldd` gives:
```
	libgalsim.so.2.3 => not found
```
when using a version built against the new galsim with the old rubin-env build.

**Comment by beckermr** [comment]
ouch. thanks for for answering my questions!

**Review by brianv0 — APPROVED** [review]

**Pull request merged**
