### PR TITLE
Use default build of clang on osx.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
This is attempt number 2.  The first attempt failed because we are constraining clang and not the variants with the versions.  I hope this works...

**Comment by erykoff** [comment]
This is now using `default` instead of `root` so I think that's good.

**Review by ktlim — APPROVED** [review]
This looks OK; the hard-coding of `clang` is not likely to be a problem, especially for 4.0.x.
You're sure we don't need this on other branches, including `main`?
The removal of the `boost` `pin_run_as_build` is also presumably not an issue, as that was due to the rerender.

**Comment by erykoff** [comment]
I hope the boost max thing is okay, since the rerenderer did that.  Boost is still coming out correct.  As for `main`, at the moment it's fine, and I filed an issue on the feedstock so hopefully they're aware and it'll continue to be fine if they do a `root` build for clang 16.  This won't work as-is because there isn't a `default_*` for `clang` on versions >= 14.  But there is for `clangxx` and it may be that we can defensively do this for later rubin-env versions.  But I haven't tested that.

**Comment by mwittgen** [comment]
It doesn't work, build 6 still installs  the root version
```
rubin-env                 4.0.5           py310hb6292c7_6    conda-forge
rubin-env-nosysroot       4.0.5           py310h7f685a7_6    conda-forge
clang                     13.0.1          root_63002_h53dd1c6_5    conda-forge
clang-13                  13.0.1          root_63002_h40c86ff_5    conda-forge
clang_osx-arm64           13.0.1               hc97ff27_5    conda-forge
clangxx                   13.0.1          root_63002_hd9466a5_5    conda-forge
clangxx_osx-arm64         13.0.1               h15d2725_5    conda-forge
libclang-cpp13            13.0.1          root_63002_h40c86ff_5    conda-forge
```

**Pull request merged**
