### PR TITLE
DM-34350: Add minimum version on moto to prevent crazy solves.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge-admin please rerender

**Review by ktlim — APPROVED** [review]
Looks good.  All other branches have moto < 3, except dev.  May need to apply this there as well?

**Comment by erykoff** [comment]
I think you're right (though py310 might add additional constraints that make that impossible).  However, it seems my fork is messed up and I'll need to refork so that would have to happen after this is merged.

**Comment by ktlim** [comment]
Dev is made to be broken anyway :)
Fine to deal with that whenever convenient (or not, so we can see problems like this).

**Pull request merged**
