### PR TITLE
DM-33347: Pin moto to < 3.0 as needed by daf_butler

### PR DESCRIPTION
**Pull request by timj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timj** [comment]
@conda-forge-admin, please rerender

**Review by ktlim — APPROVED** [review]

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Review by beckermr — CHANGES_REQUESTED** [review]
We need to be careful here. 

For things that we link against in the stackvana builds, these pins can stomp on the pins from conda-forge.

**Comment by beckermr** [comment]
See here for what I mean: https://github.com/conda-forge/stackvana-afw-feedstock/blob/master/recipe/meta.yaml#L37

**Comment by ktlim** [comment]
I'm not sure what you mean; cfitsio was already pinned at `=3` to ensure C++ compatibility.

**Comment by ktlim** [comment]
In fact, none of the packages mentioned in stackvana-afw-feedstock changed specifications at all.

**Comment by beckermr** [comment]
Ok. Conda forge is going to move to 4 soon for cfitsio for example. And then the pin here will break stackvana and compatibility generally. It might be worth putting host-like things in a separate section and letting conda-forge dictate the Abi or at least making this recipe fail if something is incompatible.

**Comment by timj** [comment]
We are planning on a 1.0.0 rubin-env soon to remove the cfitsio pin.

**Comment by beckermr** [comment]
Remove or bump to 4?

**Comment by ktlim** [comment]
OK, but that isn't for the current minimum versions; you are referring to the pre-existing equality major versions for C++ code.  We need those because our binaries that link to them will fail if linked against ABI-incompatible libraries.  We will need to update the pins and rebuild all of our software when conda-forge moves.

(And @timj, cfitsio is not one of the pins being removed.)

**Comment by beckermr** [comment]
OK. I guess when it breaks, it breaks.

**Pull request merged**
