### PR TITLE
DM-34610: Update rubin-env to v4 and add rubin-env-extras (dev branch).

### PR DESCRIPTION
**Pull request by ktlim**
* Still python 3.10.
* Add PyLD, skyproj.
* Add rubin-env-extras output including packages from sciplat-lab,
  shared_stack, sims, and add in imagemagick and ffmpeg.
* Update cfitsio to 4.1.0 and flake8 to 4.0.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
I think the conda forge python 3.10 numpy pin is at 1.21.

**Comment by erykoff** [comment]
But I still fully don't understand how the numpy pinning works.

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by ktlim** [comment]
@conda-forge-admin, please rerender

**Comment by erykoff** [comment]
Late-breaking update!  I poked the george py310 migration last night, which got Dan Foreman-Mackey's attention and he fixed it promptly:  https://github.com/conda-forge/george-feedstock/pull/15. I checked and it appears to be available now.  (But note that it is not available on osx-arm64 or aarch64).

**Comment by erykoff** [comment]
`george` isn't compatible with aarch64.  Nor is it compatible with osx-arm64, but we don't actually test anything with osx-arm64 since it's a cross-build, so that just disappears into the ether.

**Review by erykoff — APPROVED** [review]

**Pull request merged**
