### PR TITLE
Pin pydantic to version 1

### PR DESCRIPTION
**Pull request by mwittgen**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by erykoff — DISMISSED** [review]

**Comment by timj** [comment]
We decided we definitely want to pin in the v7 env then? And not rely on documenteer and fastapi unpinning their constraints and pydantic 2 appearing suddenly?

**Comment by erykoff** [comment]
I was thinking that dev is currently non operational on osx-arm64 (at least) because of this, so I feel it needs to be pinned unless we know we can unpin it.

**Comment by timj** [comment]
How did dev break? I hadn't realized since I am running 7.0.0dev locally but I installed it before pydantic 2. Did some package mess fail to pin it itself? documenteer will force pydantic<2 in its dependencies so I'm surprised it doesn't force the pin everywhere.

**Comment by erykoff** [comment]
`documenteer` is only in `rubin-env-developer`.  I guess I haven't explicitly tested that dev is broken, but I've assumed it's broken because the vanilla `osx-arm64` env gives pydantic=2 when Fabio does his weekly builds on rubin-env=6 (and also v25 with rubin-env=5).

**Comment by timj** [comment]
pydantic=2 is nominally fine for us in rubin-env 7 though, in terms of lsst_distrib.

**Comment by erykoff** [comment]
I got the week numbers mixed up, I now understand that weekly 27 (and env 7 release will be after this) should be pydantic 1 and 2 compliant.  But anybody who installs -developer will get pydantic 1 for the time being.

**Comment by erykoff** [comment]
So I think this PR should be closed.

**Pull request closed without merging**
